### ISSUE TITLE
How code is supposed to be sent to repl.co ?

### ISSUE THREAD

**Issue by Ximaz** [billythegoat356/Pandore#2]
So, I guess this is the line you use to send data to repl.co, but there is something I understand. https://github.com/billythegoat356/Pandore/blob/4f8ed6628cabcb0bba3685af85a197ad2847d0c6/main.py#L99

A post requests should looks like this :
``field=data``
But in this case, there isn't any field. How can your server understand what this part of the request is the code ?

**Comment by billythegoat356** [comment]
i didn't make any fields. i directly sent the file content in the data so my server can get it easily

**Comment by Ximaz** [comment]
> i didn't make any fields. i directly sent the file content in the data so my server can get it easily

I would rather use the ˋ`files`ˋ from the requests module then. I understand it makes it easier but still not conventional.
